### ISSUE TITLE
Any example in the docs?

### ISSUE THREAD

**Issue by dy** [CharlesStover/use-react-router#10]
Hi! 
That would be really nice to know how to use that component!
That would be really nice to have some explanation in readme, showcasing the basic routes/navigating etc.
Would really appreciate that.

**Comment by quisido** [comment]
`useReactRouter` does not implement routing. You'll need to use the [react-router](https://www.npmjs.com/package/react-router) package for that. Its documentation should showcase routing and navigation. `use-react-router` is a conversion of `react-router`'s `withRouter` HOC to a React Hook.

Hope this answers your question.

**Comment by dy** [comment]
I hoped to see some real cases code.

**Comment by lywoo-sroeng** [comment]
@dy I think this example would help you
https://qiita.com/ozaki25/items/db58152f035b0b6ae781

**Comment by quisido** [comment]
Great resource, @lywoo-sroeng . I love the visual demos.

I'm going to close this issue, because I think that resource addresses the original concern. I don't plan on having any additional documentation in this repository, since I believe that behavior belongs in the `react-router` documentation itself, not here.
