### ISSUE TITLE
Incorrect error is thrown when react-router Provider is missing.

### ISSUE THREAD

**Issue by mikecfisher** [CharlesStover/use-react-router#16]
Getting this error in the console even though I've confirmed I have react-router 5 and react-router-dom 5 installed. Any ideas why this might be happening?

**Comment by quisido** [comment]
Can you share the exact version numbers that are installed?

**Comment by CharlesStover** [comment]
Can you share the exact version numbers that are installed?

**Comment by mikecfisher** [comment]
Sure thing 
```
    "react-router": "^5.0.0",
    "react-router-dom": "5.0.0",
```

**Comment by quisido** [comment]
That's `^5.0.0`, but not the exact version, e.g. you could be using `5.0.1`, but it looks like they haven't published a later version than 5.0.0, so that shouldn't be a problem.

Do you have `react-router` installed in multiple places in the directory tree? For example, if you are in `path/to/your-app/src/`, you may have it in `path/to/your-app/node_modules/react-router`. Do you also have react-router installed in e.g. `path/to/node_modules/react-router` or `path/node_modules/react-router` or `path/to/your-app/src/node_modules/react-router`?

Are react-router/react-router-dom installed in the same `node_modules` directory and package.json file as `use-react-router`?

Can you try deleting your `node_modules` directory and re-installing it from scratch with `npm install` or `yarn`? It's possible that one package was installed with `npm` while the other was installed with `yarn`, which I believe could cause this error as well.

**Comment by mikecfisher** [comment]
Thanks @CharlesStover it was strange as I went into my node_modules folder and verified react-router and react-router-dom were both on 5.0. Anyways I just updated my Node/NPM versions and blew away node modules and reinstalled and got it working. Thanks for the help and nice job on this little library!

**Comment by quisido** [comment]
You're welcome. I'm glad it was resolved.

**Comment by veksen** [comment]
I'm getting the exact same, but only during tests. Using Jest and Create-React-App. `react-router` and `react-router-dom` are at `5.0.0` (checked node_modules). Was at Node 9, but upgraded to Node 10 without luck.

![image](https://user-images.githubusercontent.com/3461986/57986099-8174fe80-7a3e-11e9-96fa-35ad0fea88f7.png)

**Comment by quisido** [comment]
@veksen  Have you tried removing your entire node modules directly and installing it again from scratch via `yarn` or `npm install`?

**Comment by veksen** [comment]
Yes, including clearing out (deleting) yarn.lock

**Comment by fxOne** [comment]
I had the same error message and spend a lot of time to find an old react-router installation until i noticed that the issue was not the wrong react-router version but a wrong error message:
```
import React, {ReactElement, useContext} from 'react';
import { BrowserRouter as Router} from 'react-router-dom';
import useReactRouter from 'use-react-router';

export default function ():ReactElement {
  const { history, location, match } = useReactRouter();
  return  <Router>...</Router>;
}
```
My issue was the the context is not yet created which causes the error message `use-react-router may only be used with react-router@^5.`. Moving the useReactRouter a component deeper resolves my issue.

@CharlesStover maybe you can catch the error the someone wants to access the `RouterContext` outside of the `<Router>` and throw a better error?

**Comment by veksen** [comment]
@fxOne That was what I thought as I skimmed through the code and saw the error message in use when `useContext` would return `falsy`. In my case, I am not wrapping my tests in a `<Router>`, and the old tests were testing the unconnected (non `useRouter` HOC) component, so that makes sense. Perhaps let's create a new issue about the error message?

**Comment by quisido** [comment]
Thank you very much for that debugging information. I'm not sure I'd have found that on my own!

I'll go ahead and repurpose this issue with the newfound information.
