### ISSUE TITLE
Pin peerDependency of react-router

### ISSUE THREAD

**Issue by StringEpsilon** [CharlesStover/use-react-router#17]
Just giving you a heads up that you probably want to pin all your dependencies (peer or not) of react-router to "5.0.0" exactly. 

There is a open PR to rename the `__RouterContext`  export. But it's a good idea to fix the version anyway, because the context isn't part of the public API. You should check compatibility with RR manually for each new release.

**Comment by quisido** [comment]
Thanks for the heads up. I've been manually checking since alpha. I don't want to pin a dependency and force users to use a version they don't want (or have to manually push a new patch with each `react-router` patch). When they deprecate `__RouterContext`, I'll either pin it then or change to whatever API allows the context to be used.
